### ISSUE TITLE
Modal Overlay Issues in IE6

### ISSUE THREAD

**Issue by tmorehouse** [qTip2/qTip2#427]
I have a large user base of users stuck on IE6 (which i have no control over unfortunately).

The overlay works great in Firefox, Chrome, IE8+, Safari, but IE6 it doesn't display at all, and hence items in the background are clickable.

The issue lies with the use of "fixed" in the CSS positioning, and the resize event function.

I've made a minor modification to both the code and the CSS which works great (and still works in all other browsers).

Code Changes:

``` javascript
    // Update position on window resize or scroll
    function resize() {
        overlay.css({
//          height: $(window).height(), 
//          width: $(window).width()
            height: $(document).height(), // replaced with document width/height
            width: $(document).width()
        });
    }
```

CSS Changes:

``` css
#qtip-overlay{
/*  position: fixed; */ /* removed this line */
    position: absolute; /* changed to absolute */
    width: 100%; height: 100%; /* added this, but not sure if needed */
    left: -10000em;
    top: -10000em;
}
```
